name: hostel_assist
description: "Smart AI-Powered Hostel Administration App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.1
  logger: ^2.4.0
  shared_preferences: ^2.3.3
  
  # HTTP & Networking
  http: ^1.2.2
  
  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
